[package]
name = "surrealdb-vector-example"
version = "0.1.0"
edition = "2021"

[dependencies]
serde_json = "1.0.134"
surrealdb = "2.1.4"
tokio = { version = "1.42.0", features = ["macros", "rt-multi-thread"] }
