[package]
name = "csv_play"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
csv = "1.3.0"
micro_rand = "0.0.1"
names = "0.14.0"
uuid = { version = "1.7.0", features = ["v4"] }
